# disables anonymous usage statistics
[browser]
gatherUsageStats = false 

[theme]
base="dark"                
primaryColor="#E4EDA6"      # button & accent color
backgroundColor="#9cc4e5ff"   # page background
secondaryBackgroundColor="#b0d3f5ff"
textColor="#00325aff"
borderColor = "#023ca7ff"
font="sans serif" 

[client]
showSidebarNavigation = false