# disables anonymous usage statistics
[browser]
gatherUsageStats = false 

[theme]
base="dark"                # or "dark"
primaryColor="#ffffffff"      # button & accent color
backgroundColor="#9cc4e5ff"   # page background
secondaryBackgroundColor="#b0d3f5ff"
textColor="#00325aff"
borderColor = "#025da7ff"
font="sans serif" 

[client]
showSidebarNavigation = false