[auth]
redirect_uri = "http://localhost:8051/oauth2callback"
cookie_secret = "38c93793ce98eeda53bb4c396247654a3dda2816e2fd47b4821d21e9cf9fb5cf"
client_id = "87077431447-0btde8tpuqpsra8cs8kthsjch2s8n0jb.apps.googleusercontent.com"
client_secret = "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"
server_metadata_url = "https://accounts.google.com/.well-known/openid-configuration"